ARG CREATOR_SIGNAL_BACKEND_IMAGE=creator-signal-backend
FROM ${CREATOR_SIGNAL_BACKEND_IMAGE}
ARG FRONTEND_GLITCHTIP_VERSION=local
ENV GLITCHTIP_VERSION ${FRONTEND_GLITCHTIP_VERSION}

COPY dist/glitchtip-frontend/browser /code/dist

RUN SECRET_KEY=ci ./manage.py collectstatic --noinput
